"""initial schema

Revision ID: 5c012f2b797a
Revises: 
Create Date: 2026-08-05 11:14:04.760644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (ExactDecimal) render as `app.money.ExactDecimal(...)`
# in autogenerated migrations, so the module must be importable here.
import app.money


# revision identifiers, used by Alembic.
revision: str = '5c012f2b797a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('cash', 'bank', 'broker', name='accounttype', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance_cents', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('income', 'expense', name='categorykind', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_category_name_parent')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('quote', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', app.money.ExactDecimal(length=40), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base', 'quote', 'date', name='uq_fx_base_quote_date')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value_cents', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_portfolio_snapshot_date')
    )
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('exchange', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('asset_type', sa.Enum('stock', 'etf', 'fund', 'other', name='assettype', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('monthly', 'yearly', name='budgetperiod', native_enum=False), nullable=False),
    sa.Column('limit_cents', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Date(), nullable=False),
    sa.Column('rollover', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'period', name='uq_budget_category_period')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('quantity', app.money.ExactDecimal(length=40), nullable=False),
    sa.Column('avg_cost_price', app.money.ExactDecimal(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'account_id', name='uq_holding_security_account')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', app.money.ExactDecimal(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'date', name='uq_price_security_date')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_price_security_date', ['security_id', 'date'], unique=False)

    op.create_table('recurring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', 'quarterly', 'yearly', name='frequency', native_enum=False), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_generated_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('original_amount_cents', sa.Integer(), nullable=True),
    sa.Column('fx_rate', app.money.ExactDecimal(length=40), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recurring_rule_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurring_rule_id'], ['recurring_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurring_rule_id', 'due_date', name='uq_transaction_rule_due_date')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_category_date', ['category_id', 'date'], unique=False)
        batch_op.create_index('ix_transactions_date', ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_date')
        batch_op.drop_index('ix_transactions_category_date')

    op.drop_table('transactions')
    op.drop_table('recurring_rules')
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_price_security_date')

    op.drop_table('price_snapshots')
    op.drop_table('holdings')
    op.drop_table('budgets')
    op.drop_table('securities')
    op.drop_table('portfolio_snapshots')
    op.drop_table('fx_rates')
    op.drop_table('categories')
    op.drop_table('accounts')
    # ### end Alembic commands ###
